### ISSUE TITLE
Eyeball moves to the opposite direction

### ISSUE THREAD

**Issue by nya7** [nmchan/waidayo#1]
Hello, nmchan!
Sorry to write in English because my Japanese is poor. This app is a really perfect work, thanx for your development!
Here I have a problem to report. The eyeballs turn pretty well when I look up and down, but it seems that they move to the opposite direction when I look left and right (just like the picture). So I guess there maybe some problem after getting eyeballs movement data from ARKit. This problem makes me a little difficult to make my character looking straight to screen if I turn my head a little bit angle (like just 15 degrees).
Please check this, thanx :)
![Untitled-1](https://user-images.githubusercontent.com/66823533/84487663-ab483580-acd1-11ea-96e6-204e70d86cf3.png)

**Comment by nmchan** [comment]
Thanks for the report.
Give me a minute to do some research.

By the way, that's the default avatar, but the one you're using isn't causing any problems. You mean? The eyes behave quite differently for each avatar, so I'm a little concerned about them.

**Comment by nya7** [comment]
Thanks!
In fact the avatar I'm using has nearly same problem. Here I have 2 my own VRM avatars, but this default avatar is so cute XD
